### PR TITLE
graphql doc

### LINKED ISSUE #24: GraphQL API documentation
Add GraphQL api documentation to readme

### PR DESCRIPTION
**Pull request by rfabricioflores**
Documentation for graphql :)

Closes #24

### CODE REVIEW

**Review by a-jaxell — APPROVED** [review]
Very 👏 well 👏 done! 👏

**Comment by holst9559** [comment]
Very clean! Well done! :punch:
Are we going to implement GraphQL with all the other endpoints? If that's the case then maybe just write headers for that part of the documentation. :smiley:

**Comment by jakobpalmborg** [comment]
> Very clean! Well done! 👊 Are we going to implement GraphQL with all the other endpoints? If that's the case then maybe just write headers for that part of the documentation. 😃

Good idea, but I don't know if we going to implement GraphQl for all endpoints.  Maybe we could add that to readme if/when that functionality is added?

**Review by a-jaxell — APPROVED** [review]

**Comment by saeraa** [comment]
Very nice work, looking good! Was just wondering if maybe it should be in a different file and the README.md in the root directory should have a link to the documentation instead? And maybe the README in the root file should contain general information about the app.

**Comment by ved0** [comment]
> Very nice work, looking good! Was just wondering if maybe it should be in a different file and the README.md in the root directory should have a link to the documentation instead? And maybe the README in the root file should contain general information about the app.

This is a great suggestion! 👏

**Review by ved0 — APPROVED** [review]
The documentation is well written and clear. Well done guys! 🙌

**Comment by yvette809** [comment]
Well written and clear guide. It will be nice to have it for all the other graphql endpoints as someone proposed

**Comment by kappsegla** [comment]
> > Very clean! Well done! 👊 Are we going to implement GraphQL with all the other endpoints? If that's the case then maybe just write headers for that part of the documentation. 😃
> 
> Good idea, but I don't know if we going to implement GraphQl for all endpoints. Maybe we could add that to readme if/when that functionality is added?

I would say that with graphql we shouldn't be thinking in crud terms which we often do with rest endpoints. Instead we should try to create queries and mutations that are designed to fit what the frontend and other client needs and not be a direct reflection about how we are storing and organizing the data. We can for example look more into creating queries that can combine all information that is needed for one view in the frontend so we don't need to make multiple requests to different endpoints to get all the information.

**Pull request merged**
