### PR TITLE
Remove .sql files since we don't need them anymore

### PR DESCRIPTION
**Pull request by liber09**

### CODE REVIEW

**Review by jakobpalmborg — COMMENTED** [review]
Do we have functionality to add Category and Tag yet? If not, this default data might be good to have in flyway until we have that functionality in place? I think the category-table and tag-table can't be empty when you create tasks?

**Comment by solidtop** [comment]
> Do we have functionality to add Category and Tag yet? If not, this default data might be good to have in flyway until we have that functionality in place? I think the category-table and tag-table can't be empty when you create tasks?

There is a PR that handles creation of tags, but not category. Should we make a issue for creating categories?

**Review by saeraa — APPROVED** [review]
Well deleted! 👏🏻

**Comment by jakobpalmborg** [comment]
> > Do we have functionality to add Category and Tag yet? If not, this default data might be good to have in flyway until we have that functionality in place? I think the category-table and tag-table can't be empty when you create tasks?
> 
> There is a PR that handles creation of tags, but not category. Should we make a issue for creating categories?

Sounds like a good idea!

**Comment by saeraa** [comment]
> Do we have functionality to add Category and Tag yet? If not, this default data might be good to have in flyway until we have that functionality in place? I think the category-table and tag-table can't be empty when you create tasks?

See pull request #29

**Review by jakobpalmborg — APPROVED** [review]

**Pull request merged**
